blank_issues_enabled: false
contact_links:
  - name: Shizu Support
    url: https://t.me/ShizuSupport_Official
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://shizuuser.tech/
    about: Basic documentation for setting up.